from .proyectoSerializer import ProyectoSerializer
from .perfilSerializer import PerfilSerializer
from .skillsSerializer import SkillsSerializer
from .perfilEmpresaSerializer import PerfilEmpresaSerializer
from .coverSerializer import CoverSerializer
