# Generated by Django 3.2.9 on 2021-12-06 00:17

from django.db import migrations, models
import djongo.models.fields
import ms2App.models.perfil
import ms2App.models.perfilEmpresa
import ms2App.models.proyecto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('inicio', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('fin', models.CharField(max_length=2000)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('enlace', models.CharField(max_length=2000, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('institucion', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('anio', models.CharField(max_length=4)),
                ('materia', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('empresa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('funciones', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('requerimientos', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('idCover', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField()),
                ('trabajo', models.CharField(max_length=500, null=True)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('formacion', djongo.models.fields.ArrayField(blank=True, model_container=ms2App.models.perfil.Formacion, null=True)),
                ('trabajo', djongo.models.fields.ArrayField(blank=True, model_container=ms2App.models.perfil.Trabajo, null=True)),
                ('intereses', models.TextField(blank=True, null=True)),
                ('usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('sector', models.CharField(max_length=50)),
                ('vacantes', djongo.models.fields.ArrayField(model_container=ms2App.models.perfilEmpresa.Vacante)),
                ('calificacion', models.IntegerField()),
                ('anioCreacion', models.CharField(max_length=4)),
                ('usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreProyecto', models.CharField(max_length=300)),
                ('tecnologiasUsadas', djongo.models.fields.ArrayField(model_container=ms2App.models.proyecto.Tecnologia, model_form_class=ms2App.models.proyecto.TecnologiaForm)),
                ('tematica', models.CharField(max_length=300)),
                ('duracion', djongo.models.fields.EmbeddedField(model_container=ms2App.models.proyecto.Duracion, model_form_class=ms2App.models.proyecto.DuracionForm)),
                ('descripcionProyecto', models.CharField(max_length=2000)),
                ('enlaces', djongo.models.fields.ArrayField(model_container=ms2App.models.proyecto.Enlaces, model_form_class=ms2App.models.proyecto.EnlacesForm)),
                ('usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('idSkills', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('experiencia', models.CharField(max_length=500, null=True)),
                ('dominio', models.CharField(max_length=500, null=True)),
                ('usuario', models.IntegerField()),
            ],
        ),
    ]
