# Generated by Django 3.2.9 on 2021-11-28 22:59

from django.db import migrations, models
import djongo.models.fields
import ms2App.models.perfil


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('institucion', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('anio', models.CharField(max_length=4)),
                ('materia', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('empresa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
                ('funciones', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('descripcion', models.TextField()),
                ('metodologia', models.TextField()),
                ('formacion', djongo.models.fields.ArrayField(model_container=ms2App.models.perfil.Formacion)),
                ('trabajo', djongo.models.fields.ArrayField(model_container=ms2App.models.perfil.Trabajo)),
                ('intereses', models.TextField()),
                ('usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
